@startuml
    skinparam class {
        BackgroundColor #ffffff
        ArrowColor #0000FF
    }

    hide circle

    Class GestorLloguersLite {

	+ GestorLloguersLite(): void
	
	+ nouLloguer(fecha: String, dias: Integer, categoria: String): Lloguer
	
	+ {static} quantitat(Lloguer lloguer): double

    }
@enduml